version: "3.9"
services:
  apache-server:
    container_name: nginx-https
    image: nginx-https:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:443
      #- 80:80
